version: '3.9'

###############################
####      Services
###############################
services:

  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERDIR}/portainer/data:/data
    environment:
      - TZ=${TZ}

  # ResilioSync - PrivateCloud
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    restart: unless-stopped
    networks:
      - default
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/appdata/rslsync/config:/config
      - ${DOCKERDIR}/rslsync/downloads:/downloads
      - ${DOCKERDIR}/rslsync/downloads:/sync
    ports:
      - 8888:8888
      - 55555:55555

  # DuckDNS - Dynamic DNS provider
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=${TZ} #optional
      - SUBDOMAINS=$DuckDNSSUBDOMAIN
      - TOKEN=$DuckDNSTOKEN
      - LOG_FILE=false
    volumes:
      - ${DOCKERDIR}/duckdns/appdata/config:/config #optional
    restart: unless-stopped
  # WireGuard - VPN provider
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    # mac_address: d0:ca:ab:cd:ef:03
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SERVERURL=$DuckDNSSUBDOMAIN
      - SERVERPORT=51820
      - PEERS=7
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0 #Only change if it conflicts
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ${DOCKERDIR}/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      macvlan:
        ipv4_address: ${WIREGUARD_MACVLAN_IP}
    restart: unless-stopped

  # Pihole - Ads Blocker
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    # mac_address: d0:ca:ab:cd:ef:01
    #     cap_add: # Uncomment if you want to use Pi-Hole for DHCP
    #       - NET_ADMIN
    ports:
      - 53/tcp
      - 53/udp
      - 80/tcp
    environment:
      - FTLCONF_LOCAL_IPV4=${PIHOLE_MACVLAN_IP}
      - WEBPASSWORD=${PiHoleWEBPASSWORD}
      - PIHOLE_DNS_=${UNBOUND_MACVLAN_IP}
      - DNSMASQ_USER=root
      - DNSMASQ_LISTENING=all
    volumes:
      - ${DOCKERDIR}/pihole-unbound/pihole/volume:/etc/pihole:rw
      - ${DOCKERDIR}/pihole-unbound/pihole/config/dnsmasq.conf:/etc/dnsmasq.d/:rw
    networks:
      macvlan:
        ipv4_address: ${PIHOLE_MACVLAN_IP}
    restart: always

  # Unbound
  unbound:
    container_name: unboundn
    image: mvance/$UnboundImage:latest
    hostname: syn-unbound
    # mac_address: d0:ca:ab:cd:ef:02
    ports:
      - 53/tcp
      - 53/udp
    networks:
      macvlan:
        ipv4_address: ${UNBOUND_MACVLAN_IP}
    restart: always
  ###############################
  ####      Networks
  ###############################
networks:
  default:
    driver: bridge
  macvlan:
    driver: macvlan
    driver_opts:
      parent: $parentNet
    ipam:
      config:
        - subnet: ${MACVLAN_SUBNET}
          gateway: ${MACVLAN_GATEWAY}
          ip_range: ${MACVLAN_IP_RANGE}
